### PR TITLE
Refactor TLV XOR, add UUID to each packet, remove core_uuid, add core_set_uuid

### PR DESCRIPTION
**Pull request by OJ**
This PR has a partner PR in the MSF repo that has all the detail in it. This can be found here: https://github.com/rapid7/metasploit-framework/pull/7507

Thanks.

### CODE REVIEW

**Comment by busterb** [comment]
Fixed up posix, I'm going to land this so we can have some test builds available. This is going to be the first build for 1.2.x since this is ABI-changing.

**Comment by OJ** [comment]
That's Brent. What was up with POSIX? I thought I'd fixed it up already :-/

**Comment by busterb** [comment]
e5f695fde783a6b68e9c0345410cda7fffb755cd

**Comment by OJ** [comment]
Crap. Why the hell did that build locally for me then?

Sorry about that.

**Pull request merged**
