### PR TITLE
Do not reissue closed channel ids in the Python Meterpreter

### PR DESCRIPTION
**Pull request by zeroSteiner**
This is a quick fix / workaround for rapid7/metasploit-framework#6593. While debugging this issue I came across an odd issue caused by the finalize method in [channel.rb](https://github.com/rapid7/metasploit-framework/blob/master/lib/rex/post/meterpreter/channel.rb#L147-149). What appears to be happening is the channel is being explicitly closed once, and then closed a second time when the channel object is garbage collected. In the case of the Python Meterpreter this was causing a channel to be prematurely closed due to the fact that it would reissue channel IDs after they had been closed.

The issue was manifesting itself when a large file was being downloaded a second time. During the course of the second download the previous channel was garbage collected and it's ID closed for a second time. Due to it being reissued by the Python meterpreter this cid could (and sometimes is) in use.

This change introduces a work around by not reissuing channel IDs which have been closed. The following is output from the Python Meterpreter with the `PythonMeterpreterDebug` option set to true. Notice channel ID 1 is closed, then channel id 2 is opened read and finally channel id 1 is closed again resulting in an expected error.

```
[*] running method core_channel_read
[*] running method core_channel_read
[*] running method core_channel_eof
[*] running method core_channel_close
[*] closed and removed channel id: 1
[*] running method stdapi_fs_stat
[*] running method core_channel_open
[*] added channel id: 2 type: MeterpreterFile
[*] running method stdapi_fs_stat
[*] running method core_channel_read
[*] running method core_channel_read
[*] running method core_channel_read
[*] running method core_channel_read
[*] running method core_channel_read
[*] running method core_channel_read
[*] running method core_channel_read
[*] running method core_channel_read
[*] running method core_channel_read
[*] running method core_channel_read
[*] running method core_channel_close
[-] method core_channel_close resulted in error: #1
[*] running method core_channel_read
[*] running method core_channel_read
```

Testing:
 - [x] Get a Python Meterpreter session with debugging enabled
 - [x] Quickly download a large file twice in a row (Removing it in between or use two different ones)
 - [x] Notice that a core_channel_close call resulted in a failure in the debug logs
 - [x] Ensure that the second time the file is downloaded the entire contents are available and the hash matches what was expected

CC @mubix

### CODE REVIEW

**Comment by OJ** [comment]
Jenkins add to whitelist

**Comment by bcook-r7** [comment]
Looks good, landing to build a test gem with the fixes.

**Comment by bcook-r7** [comment]
oh my gosh - I suddenly remembered the duplicate close requests on registry keys from last year - I wonder if they have a similar finalizer issue!

**Comment by zeroSteiner** [comment]
Thanks @bcook-r7 !

**Pull request merged**
