### PR TITLE
Remove all debug builds from the Windows projects

### PR DESCRIPTION
**Pull request by OJ**
The debug builds of Meterpreter compiled fine, but the resulting binaries were never functional. No debugging is really ever done with the debug builds anyway, so instead of carry them forward, this commit removes both `debug` and `r7_debug` from the source.

## Verification

- [ ] Build Windows Meterrpeter.
- [ ] It doesn't fail to build.
- [ ] Resulting binaries are still copied to the appropriate location.

### CODE REVIEW

**Comment by OJ** [comment]
I chatted to @bcook-r7 about this behind the scenes, and he was on board with it.

**Comment by bcook-r7** [comment]
Thanks, glad we got rid of these.

**Comment by jlee-r7** [comment]
Agreed. I wish Visual Studio didn't suck so bad at managing build targets.

**Comment by OJ** [comment]
Thanks all!

**Pull request merged**
