### PR TITLE
Use RtlGetVersion to detect version

### PR DESCRIPTION
**Pull request by OJ**
This PR moves over to the `ntdll` function `RtlGetVersion` to get the version information for the current OS. This means we can actually correctly detect the version of Windows in use past 8.1 (ie including 10 and later).

According to the docs, this is supported in versions of Windows all the way back to 2000, so should be fully backwards compat.

### Sample runs
This PR was tested on Windows 7 x64 as x86:
```
meterpreter > sysinfo
Computer        : WIN-S45GUQ5KGVK
OS              : Windows 7 (Build 7601, Service Pack 1).
Architecture    : x64 (Current Process is WOW64)
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x86/win32
```
Windows 7 x64 as x64:
```
meterpreter > sysinfo
Computer        : WIN-S45GUQ5KGVK
OS              : Windows 7 (Build 7601, Service Pack 1).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x64/win64
```
Windows 2012 x64 as x64:
```
meterpreter > sysinfo
Computer        : PDC2012
OS              : Windows 2012 (Build 9200).
Architecture    : x64
System Language : en_US
Domain          : PWNAGE
Logged On Users : 5
Meterpreter     : x64/win64
```
Windows 8.1 x64 as x64:
```
meterpreter > sysinfo
Computer        : WIN-8RDFKU33NLH
OS              : Windows 8.1 (Build 9600).
Architecture    : x64
System Language : en_GB
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x64/win64
```
Windows XP SP3 x86:
```
meterpreter > sysinfo
Computer        : OJ-75E3B8CC9475
OS              : Windows XP (Build 2600, Service Pack 3).
Architecture    : x86
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x86/win32
```

And finally Windows 10 x64 as x86:
```
meterpreter > sysinfo
Computer        : DESKTOP-M9H28RB
OS              : Windows 10 (Build 10240).
Architecture    : x64 (Current Process is WOW64)
System Language : en_AU
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x86/win32
```
and Windows 10 x64 as x64:
```
meterpreter > sysinfo
Computer        : DESKTOP-M9H28RB
OS              : Windows 10 (Build 10240).
Architecture    : x64
System Language : en_AU
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x64/win64
```

Note that the version for Windows 10 is correctly identified.

### Verification
- [x] Launch a bunch of sessions on various versions of Windows, including Windows 10
- [x] Version information should function as it used to on older versions.
- [x] Windows 10 is correctly identified.

### CODE REVIEW

**Comment by OJ** [comment]
This should fix https://github.com/rapid7/metasploit-framework/issues/5923

**Comment by bcook-r7** [comment]
LGTM, XP to 10
```
Computer        : DESKTOP-2EDRCHV
OS              : Windows 10 (Build 10240).
Architecture    : x64 (Current Process is WOW64)
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x86/win32
```

**Comment by busterb** [comment]
```
meterpreter > sysinfo
Computer        : MSF-DEV
OS              : Windows 8 (Build 9200).
Architecture    : x64 (Current Process is WOW64)
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x86/win32

Computer        : BRENT-4D9EAB94D
OS              : Windows XP (Build 2600, Service Pack 3).
Architecture    : x86
System Language : en_US
Domain          : HAUSCHEN
Logged On Users : 2
Meterpreter     : x86/win32
```

**Comment by hmoore-r7** [comment]
:exclamation: :smile:

**Comment by OJ** [comment]
Swoit! Cheers!

**Pull request merged**
