### PR TITLE
Changes to support maven 3.3+ (Ubuntu 15.10+)

### PR DESCRIPTION
**Pull request by hmoore-r7**
This bumps the android-maven plugin to 4.0.0-rc2 and moves the AndroidManfest.xml & res directories to satisfy the new requirements. Required to build with Maven versions newer than 3.2.x or so.

### CODE REVIEW

**Comment by hmoore-r7** [comment]
jenkins, this is ok to test

**Comment by bcook-r7** [comment]
This possibly breaks the automatic build system; we're building on ubuntu 14.04.2, which comes with maven 3.0. Do we now need to update the docker image to include maven 3.2 or greater?

**Comment by bcook-r7** [comment]
I just checked it out, and things do continue to work with maven 3.0 as well :)

**Comment by bcook-r7** [comment]
jenkins, add to whitelist

**Comment by bcook-r7** [comment]
Seems to work fine, merging so we can get some gem testing.

**Comment by bcook-r7** [comment]
Actually, gonna hold of a little bit so we can get all of the other recent changes through the spin cycle.

**Pull request merged**
