### PR TITLE
Encode name characters

### PR DESCRIPTION
**Pull request by scriptjunkie**
Usernames can be unicode characters too.

### CODE REVIEW

**Comment by scriptjunkie** [comment]
To reproduce, run "net user नमस्ते /add" in an admin prompt, then log in as नमस्ते and run a meterpreter. (the name might display as boxes in cmd/powershell if that isn't your native language pack, but it will still work)

**Comment by scriptjunkie** [comment]
Can also check session.sys.config.getenvs("USERNAME") and see if that works.

**Comment by wvu-r7** [comment]
A wild @scriptjunkie appears.

**Comment by scriptjunkie** [comment]
inorite

**Comment by busterb** [comment]
@bwatters-r7 I'm going to go ahead and land this to get a payloads build with #249 along for the ride

**Pull request merged**
