### PR TITLE
replace timestomp code

### PR DESCRIPTION
**Pull request by busterb**
This rewrites and removes the GPL code from timestomp in the priv extension.

## Verification

 - [ ] make a directory and create some files in it
 - [ ] open a meterpreter session, switch to this directory
 - [ ] observe output of ls
 - [ ] run 'timestomp file -v'
 - [ ] **Verify** that the MACE attributes show in msfconsole
 - [ ] run 'timestomp file -b'
 - [ ] **Verify** that the 'ls' command shows weird timestamps now from the year 2106
 - [ ] **Verify** that the 'timestomp file -v' command shows timestamps from the year 1601
 - [ ] run 'timestomp directory -r'
 - [ ] **Verify** that the subdirectories and files show blanked timestamps

For more things to try, see https://www.offensive-security.com/metasploit-unleashed/timestomp/

### CODE REVIEW

**Comment by busterb** [comment]
OK, tested locally, this should be ready to go.

**Comment by bwatters-r7** [comment]
## Testing
```
meterpreter > ls
Listing: C:\test_folder
=======================

Mode              Size  Type  Last modified              Name
----              ----  ----  -------------              ----
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (10).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (11).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (2).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (3).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (4).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (5).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (6).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (7).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (8).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (9).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy.txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document.txt
40777/rwxrwxrwx   0     dir   2017-01-24 19:36:28 -0600  test_folder2

meterpreter > timestomp -v 'New Text Document.txt'
Modified      : 2017-01-24 19:36:07 -0600
Accessed      : 2017-01-24 19:36:07 -0600
Created       : 2017-01-24 19:36:07 -0600
Entry Modified: 2017-01-24 19:36:08 -0600
meterpreter > timestomp -b 'New Text Document.txt'
[*] Blanking file MACE attributes on New Text Document.txt
meterpreter > timestomp -v 'New Text Document.txt'
Modified      : 2106-02-07 00:28:15 -0600
Accessed      : 2106-02-07 00:28:15 -0600
Created       : 2106-02-07 00:28:15 -0600
Entry Modified: 2106-02-07 00:28:15 -0600
meterpreter > ls
Listing: C:\test_folder
=======================

Mode              Size  Type  Last modified              Name
----              ----  ----  -------------              ----
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (10).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (11).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (2).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (3).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (4).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (5).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (6).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (7).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (8).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (9).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy.txt
100666/rw-rw-rw-  0     fil   2106-02-07 00:28:15 -0600  New Text Document.txt
40777/rwxrwxrwx   0     dir   2017-01-24 19:36:28 -0600  test_folder2

meterpreter > ls test_folder2
Listing: test_folder2
=====================

Mode              Size  Type  Last modified              Name
----              ----  ----  -------------              ----
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (10).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (11).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (2).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (3).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (4).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (5).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (6).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (7).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (8).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy (9).txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document - Copy.txt
100666/rw-rw-rw-  0     fil   2017-01-24 19:36:07 -0600  New Text Document.txt

meterpreter > timestomp -r test_folder2
[*] Blanking directory MACE attributes on test_folder2
meterpreter > ls test_folder2
Listing: test_folder2
=====================

Mode              Size  Type  Last modified              Name
----              ----  ----  -------------              ----
100666/rw-rw-rw-  0     fil   2106-02-07 00:28:15 -0600  New Text Document - Copy (10).txt
100666/rw-rw-rw-  0     fil   2106-02-07 00:28:15 -0600  New Text Document - Copy (11).txt
100666/rw-rw-rw-  0     fil   2106-02-07 00:28:15 -0600  New Text Document - Copy (2).txt
100666/rw-rw-rw-  0     fil   2106-02-07 00:28:15 -0600  New Text Document - Copy (3).txt
100666/rw-rw-rw-  0     fil   2106-02-07 00:28:15 -0600  New Text Document - Copy (4).txt
100666/rw-rw-rw-  0     fil   2106-02-07 00:28:15 -0600  New Text Document - Copy (5).txt
100666/rw-rw-rw-  0     fil   2106-02-07 00:28:15 -0600  New Text Document - Copy (6).txt
100666/rw-rw-rw-  0     fil   2106-02-07 00:28:15 -0600  New Text Document - Copy (7).txt
100666/rw-rw-rw-  0     fil   2106-02-07 00:28:15 -0600  New Text Document - Copy (8).txt
100666/rw-rw-rw-  0     fil   2106-02-07 00:28:15 -0600  New Text Document - Copy (9).txt
100666/rw-rw-rw-  0     fil   2106-02-07 00:28:15 -0600  New Text Document - Copy.txt
100666/rw-rw-rw-  0     fil   2106-02-07 00:28:15 -0600  New Text Document.txt

meterpreter > timestomp -v 'test_folder2/New Text Document.txt'
Modified      : 2106-02-07 00:28:15 -0600
Accessed      : 2106-02-07 00:28:15 -0600
Created       : 2106-02-07 00:28:15 -0600
Entry Modified: 2106-02-07 00:28:15 -0600
meterpreter > 
```

**Comment by busterb** [comment]
Thank you sir!

**Comment by bwatters-r7** [comment]
# Release Notes
This removes some GPL code that found its way into the codebase.

**Pull request merged**
