### PR TITLE
Revert "Undo commit for #441" (revert the revert of the merge that was correct to begin with)

### PR DESCRIPTION
**Pull request by wvu-r7**
This reverts commit 8361d5367a7400d166da3c8b772077aa9a0a793e, reversing changes made to db3d5f0896ac74b3918387be24de1e994451820d. We were stuck in a temporal loop.

Fixes #442?

### CODE REVIEW

**Comment by OJ** [comment]
OK to be clear, this looks fine to me. But I still have no idea why merging #441 resulted in things going the way they did. They weren't in @justinsteven's commit and I merged into a clean clone of `master`.

ugh

**Comment by OJ** [comment]
This LGTM. Thank you @wvu-r7 and @pbarry-r7 for the help behind the scenes to ease my panic.

**Comment by justinsteven** [comment]
Thanks @OJ @wvu-r7 @pbarry-r7!

I'm going to crawl back into my hole now :sweat_smile:

**Review by smcintyre-r7 — APPROVED** [review]

**Comment by wvu-r7** [comment]
This is why you don't mess with spacetime, @OJ. Who knows how many paradoxes you created!

Extra thanks to @smcintyre-r7 for confirming that the timeline has been restored.

**Comment by OJ** [comment]
Yes, thanks @smcintyre-r7 !!

**Pull request merged**
