### PR TITLE
Add A Debug Configuration And Fix A Check

### PR DESCRIPTION
**Pull request by zeroSteiner**
This makes the following two changes to the Windows Meterpreter.

* Commit f9e62ba adds a debug configuration to all of the relevant project files that then defines `DEBUGTRACE` which allows users to make a build that will generate debug messages with the flip of a switch
* Commit c91174943 fixes a check condition that from my testing was causing a crash when the returned channel was `NULL`. You'll note how the variable that is checked is 1) checked twice, and 2) not aligned with the debug messaging.

These changes I made while debugging rapid7/metasploit-framework#14506. There seems to be a couple of issues that pop up when there is a lot of TCP channel through put but the one I fixed came up multiple times and was straight forward to correct.

<details>
<summary>Debug Logs From Bug Fixed In c9117494</summary>

Notice how the channel is reported to be `0x00000000` right before the crash which does look like NULL pointer dereference.

```
[0bdc] [PKT FIND] TLV header length: 12
[0bdc] [PKT FIND] TLV header type: 132602
[2fe8] [PKT FIND] Found!
[2fe8] [PACKET] Sent packet to remote, length: 160, command id: 1, result: 0
[0bdc] [PKT FIND] wrong index, skipping.
[2fe8] [COMMAND] Calling completion handlers...
[2fe8] [PKT FIND] Looking for type 65538
[0bdc] [PKT FIND] TLV header length: 12
[2fe8] [PKT FIND] TLV header length: 12
[2fe8] [PKT FIND] TLV header type: 131073
[0bdc] [PKT FIND] TLV header type: 131122
[0bdc] [PKT FIND] wrong index, skipping.
[2fe8] [PKT FIND] Types don't match, skipping.
[0bdc] [PKT FIND] Reached end of packet buffer
[2fe8] [PKT FIND] TLV header length: 41
[2fe8] [PKT FIND] TLV header type: 65538
[0bdc] [DISPATCH] Packet type for 1026 is 0
[0bdc] [DISPATCH] executing request handler 1026
[2fe8] [PKT FIND] Found!
[2fe8] [COMMAND] Completion handlers finished for 1.
[0bdc] [TCP] entering request_net_socket_tcp_shutdown
[2fe8] [COMMAND] Packet is not local, destroying
[2078] [TCP] Packet receive finished
[0bdc] [PKT FIND] Looking for type 131073
[0bdc] [PKT FIND] TLV header length: 12
[2fe8] [COMMAND] Packet destroyed
[0bdc] [PKT FIND] TLV header type: 131073
[2fe8] [COMMAND] Command processing finishing. Returning: TRUE
[0bdc] [PKT FIND] Found!
[2078] [PKT FIND] Looking for type 131073
[0bdc] [PKT FIND] Looking for type 65538
[2fe8] [COMMAND] Executed inline -> Commands: 02703548 Command1: 005EF1EC Command2: 00000000
[0bdc] [PKT FIND] TLV header length: 12
[2fe8] [COMMAND] Cleaning up commands
[0bdc] [PKT FIND] TLV header type: 131073
[0bdc] [PKT FIND] Types don't match, skipping.
[0bdc] [PKT FIND] TLV header length: 41
[2078] [PKT FIND] TLV header length: 12
[0bdc] [PKT FIND] TLV header type: 65538
[2078] [PKT FIND] TLV header type: 131073
[2078] [PKT FIND] Found!
[0bdc] [PKT FIND] Found!
[2078] [COMMAND EXEC] Attempting to locate base command 1
[0bdc] [PKT FIND] Looking for type 131122
[2078] [COMMAND EXEC] Attempting to locate extension command 1 (02765AC0)
[0bdc] [PKT FIND] TLV header length: 12
[2078] [COMMAND EXEC] Couldn't find extension command 1
[2078] [DISPATCH] Executing in thread: 1
[2078] [DISPATCH] created command_process_thread 0x027023D0, handle=0x00000410
[2078] [DISPATCH] command_process result: continue
[0bdc] [PKT FIND] TLV header type: 131073
[0bdc] [PKT FIND] Types don't match, skipping.
[2078] [TCP PACKET RECEIVE] reading in the header
[25d4] [COMMAND] executing in thread 027023D0
[25d4] [COMMAND] About to execute inline -> Commands: 02703548 Command1: 005EF1EC Command2: 00000000
[2078] [TCP] the XOR key is: 9c93a7d5
[25d4] [COMMAND] Executing command 1
[2078] [TCP] Packet header: [0x9C 0x93 0xA7 0xD5] [0xD8 0xD0 0x41 0xB5 0x53 0xE3 0xE5 0x4B 0x2E 0x96 0x3B 0xC7 0x99 0x95 0xDB 0xAE] [0x9C 0x93 0xA7 0xD4] [0x9C 0x93 0xA4 0x8D] [0x9C 0x93 0xA7 0xD5]
[25d4] [PKT FIND] Looking for type 0
[2078] [TCP] XOR key looks fine, moving on
[2078] [XOR] XORing 28 bytes with key 9c93a7d5
[2078] [TCP] Packet header: [0x9C 0x93 0xA7 0xD5] [0x44 0x43 0xE6 0x60 0xCF 0x70 0x42 0x9E 0xB2 0x05 0x9C 0x12 0x05 0x06 0x7C 0x7B] [0x00 0x00 0x00 0x01] [0x00 0x00 0x03 0x58] [0x00 0x00 0x00 0x00]
[2078] [TCP] Payload length is 848
[2078] [TCP] total buffer size for the packet is 880
[2078] [TCP] Allocated packet buffer at 02713FD0
[25d4] [PKT FIND] TLV header length: 12
[2078] [TCP] Packet Session GUID: 4443E660CF70429EB2059C1205067C7B
[2078] [TCP] Session GUIDs match (or packet guid is null), decrypting packet
[2078] [DEC] Packet header: [0x9C 0x93 0xA7 0xD5] [0xD8 0xD0 0x41 0xB5 0x53 0xE3 0xE5 0x4B 0x2E 0x96 0x3B 0xC7 0x99 0x95 0xDB 0xAE] [0x9C 0x93 0xA7 0xD4] [0x9C 0x93 0xA4 0x8D] [0x9C 0x93 0xA7 0xD5]
[2078] [DEC] Packet buffer size is: 880
[2078] [XOR] XORing 876 bytes with key 9c93a7d5
[0bdc] [PKT FIND] TLV header length: 41
[2078] [DEC] Packet header: [0x9C 0x93 0xA7 0xD5] [0x44 0x43 0xE6 0x60 0xCF 0x70 0x42 0x9E 0xB2 0x05 0x9C 0x12 0x05 0x06 0x7C 0x7B] [0x00 0x00 0x00 0x01] [0x00 0x00 0x03 0x58] [0x00 0x00 0x00 0x00]
[25d4] [PKT FIND] TLV header type: 131073
[25d4] [PKT FIND] Found!
[2078] [DEC] Encryption flags set to 1
[25d4] [PKT FIND] Looking for type 0
[2078] [DEC] Context is valid, moving on ...
[25d4] [PKT FIND] TLV header length: 12
[0bdc] [PKT FIND] TLV header type: 65538
[2078] [DEC] IV: 7785DC4BDD67390707F80976A514EDF0
[0bdc] [PKT FIND] Types don't match, skipping.
[25d4] [PKT FIND] TLV header type: 131073
[0bdc] [PKT FIND] TLV header length: 12
[2078] [DEC] Encrypted Size: 832 (340)
[25d4] [PKT FIND] wrong index, skipping.
[25d4] [PKT FIND] TLV header length: 41
[0bdc] [PKT FIND] TLV header type: 132602
[2078] [DEC] Encrypted Size mod AES256_BLOCKSIZE: 0
[25d4] [PKT FIND] TLV header type: 65538
[0bdc] [PKT FIND] Types don't match, skipping.
[25d4] [PKT FIND] Found!
[0bdc] [PKT FIND] TLV header length: 12
[0bdc] [PKT FIND] TLV header type: 131122
[25d4] [PKT FIND] Looking for type 0
[0bdc] [PKT FIND] Found!
[0bdc] [PKT FIND] Looking for type 132602
[0bdc] [PKT FIND] TLV header length: 12
[25d4] [PKT FIND] TLV header length: 12
[0bdc] [PKT FIND] TLV header type: 131073
[0bdc] [PKT FIND] Types don't match, skipping.
[0bdc] [PKT FIND] TLV header length: 41
[0bdc] [PKT FIND] TLV header type: 65538
[0bdc] [PKT FIND] Types don't match, skipping.
[0bdc] [PKT FIND] TLV header length: 12
[0bdc] [PKT FIND] TLV header type: 132602
[25d4] [PKT FIND] TLV header type: 131073
[0bdc] [PKT FIND] Found!
[25d4] [PKT FIND] wrong index, skipping.
[25d4] [PKT FIND] TLV header length: 41
[0bdc] [TCP] request_net_socket_tcp_shutdown. channel=0x00000000, cid=61
(108c.bdc): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
005c3ae4 8b4018          mov     eax,dword ptr [eax+18h] ds:002b:00000018=????????
0:004:x86> ~.
.  4  Id: 108c.bdc Suspend: 1 Teb: 003bd000 Unfrozen
      Start: 005ce37e
      Priority: 0  Priority class: 32  Affinity: f
0:004:x86> r
eax=00000000 ebx=00000000 ecx=766357bb edx=00000000 esi=00000000 edi=0000003d
eip=005c3ae4 esp=023bfe88 ebp=023bfe88 iopl=0         nv up ei pl zr na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010246
005c3ae4 8b4018          mov     eax,dword ptr [eax+18h] ds:002b:00000018=????????
0:004:x86> dd eax
00000000  ???????? ???????? ???????? ????????
00000010  ???????? ???????? ???????? ????????
00000020  ???????? ???????? ???????? ????????
00000030  ???????? ???????? ???????? ????????
00000040  ???????? ???????? ???????? ????????
00000050  ???????? ???????? ???????? ????????
00000060  ???????? ???????? ???????? ????????
00000070  ???????? ???????? ???????? ????????
0:004:x86> !analyze -v
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************

*** WARNING: Unable to verify checksum for ab.exe
*** ERROR: Module load completed but symbols could not be loaded for ab.exe
GetUrlPageData2 (WinHttp) failed: 12002.

KEY_VALUES_STRING: 1


TIMELINE_ANALYSIS: 1

Timeline: !analyze.Start
    Name: <blank>
    Time: 2020-12-18T20:41:23.601Z
    Diff: 601 mSec

Timeline: Dump.Current
    Name: <blank>
    Time: 2020-12-18T20:41:23.0Z
    Diff: 0 mSec

Timeline: Process.Start
    Name: <blank>
    Time: 2020-12-18T20:16:46.0Z
    Diff: 1477000 mSec

Timeline: OS.Boot
    Name: <blank>
    Time: 2020-12-18T15:14:53.0Z
    Diff: 19590000 mSec


DUMP_CLASS: 2

DUMP_QUALIFIER: 0

FAULTING_IP:
+0
005c3ae4 8b4018          mov     eax,dword ptr [eax+18h]

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 005c3ae4
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 00000000
   Parameter[1]: 00000018
Attempt to read from address 00000018

FAULTING_THREAD:  00000bdc

DEFAULT_BUCKET_ID:  NULL_CLASS_PTR_READ

PROCESS_NAME:  ab.exe

FOLLOWUP_IP:
ntdll_77680000!__RtlUserThreadStart+2f
776e662d e92fca0300      jmp     ntdll_77680000!__RtlUserThreadStart+0x3ca63 (77723061)

READ_ADDRESS:  00000018

ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

EXCEPTION_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

EXCEPTION_CODE_STR:  c0000005

EXCEPTION_PARAMETER1:  00000000

EXCEPTION_PARAMETER2:  00000018

WATSON_BKT_PROCSTAMP:  4a2cb3e6

WATSON_BKT_PROCVER:  2.2.14.0

PROCESS_VER_PRODUCT:  Apache HTTP Server

WATSON_BKT_MODULE:  unknown

WATSON_BKT_MODVER:  0.0.0.0

WATSON_BKT_MODOFFSET:  5c3ae4

WATSON_BKT_MODSTAMP:  bbbbbbb4

BUILD_VERSION_STRING:  17763.1.amd64fre.rs5_release.180914-1434

MODLIST_WITH_TSCHKSUM_HASH:  8754c104c727d5a258b1faba500fdcb7e7219205

MODLIST_SHA1_HASH:  b781d410c6baaf8cf6b84f30ba91cf9b16fc5b82

NTGLOBALFLAG:  70

PROCESS_BAM_CURRENT_THROTTLED: 0

PROCESS_BAM_PREVIOUS_THROTTLED: 0

APPLICATION_VERIFIER_FLAGS:  0

PRODUCT_TYPE:  1

SUITE_MASK:  272

DUMP_TYPE:  fe

ANALYSIS_SESSION_HOST:  WIN10DEV

ANALYSIS_SESSION_TIME:  12-18-2020 15:41:23.0601

ANALYSIS_VERSION: 10.0.17134.226 amd64fre

IP_ON_HEAP:  00a4616d
The fault address in not in any loaded module, please check your build's rebase
log at <releasedir>\bin\build_logs\timebuild\ntrebase.log for module which may
contain the address if it were loaded.

THREAD_ATTRIBUTES:
OS_LOCALE:  ENU

PROBLEM_CLASSES:

    ID:     [0n309]
    Type:   [@ACCESS_VIOLATION]
    Class:  Addendum
    Scope:  BUCKET_ID
    Name:   Omit
    Data:   Omit
    PID:    [Unspecified]
    TID:    [0xbdc]
    Frame:  [0] : unknown!unknown

    ID:     [0n281]
    Type:   [INVALID_POINTER_READ]
    Class:  Primary
    Scope:  BUCKET_ID
    Name:   Add
    Data:   Omit
    PID:    [Unspecified]
    TID:    [0xbdc]
    Frame:  [0] : unknown!unknown

    ID:     [0n306]
    Type:   [NULL_CLASS_PTR_READ]
    Class:  Primary
    Scope:  DEFAULT_BUCKET_ID (Failure Bucket ID prefix)
            BUCKET_ID
    Name:   Add
    Data:   Omit
    PID:    [0x108c]
    TID:    [0xbdc]
    Frame:  [0] : unknown!unknown

    ID:     [0n156]
    Type:   [ZEROED_STACK]
    Class:  Addendum
    Scope:  BUCKET_ID
    Name:   Add
    Data:   Omit
    PID:    [0x108c]
    TID:    [0xbdc]
    Frame:  [0] : unknown!unknown

BUGCHECK_STR:  APPLICATION_FAULT_NULL_CLASS_PTR_READ_INVALID_POINTER_READ_ZEROED_STACK

PRIMARY_PROBLEM_CLASS:  APPLICATION_FAULT

FRAME_ONE_INVALID: 1

LAST_CONTROL_TRANSFER:  from 00a4616d to 005c3ae4

STACK_TEXT:
WARNING: Frame IP not in any known module. Following frames may be wrong.
023bfe88 00a4616d 00000000 00a8933c 00000000 0x5c3ae4
023bfec8 005c164e 0061be28 027034a8 005f0090 0xa4616d
023bff28 005c144b 00000000 006f2970 0061be28 0x5c164e
023bff64 005ce38d 027034a8 023bff80 75630419 0x5c144b
023bff70 75630419 0270e4d8 75630400 023bffdc 0x5ce38d
023bff80 776e662d 0270e4d8 ad421d48 00000000 KERNEL32!BaseThreadInitThunk+0x19
023bffdc 776e65fd ffffffff 777051e4 00000000 ntdll_77680000!__RtlUserThreadStart+0x2f
023bffec 00000000 005ce37e 0270e4d8 00000000 ntdll_77680000!_RtlUserThreadStart+0x1b


STACK_COMMAND:  ~4s ; .cxr ; kb

THREAD_SHA1_HASH_MOD_FUNC:  d451522cccd4c06f4ef787ae62773a9588131f42

THREAD_SHA1_HASH_MOD_FUNC_OFFSET:  cca17c9af84d21a162e3624a349b84361157bc17

THREAD_SHA1_HASH_MOD:  bbabcc2456a005f536a70a4260d2ed4875d85fa2

FAULT_INSTR_CODE:  3ca2fe9

SYMBOL_STACK_INDEX:  6

SYMBOL_NAME:  ntdll_77680000!__RtlUserThreadStart+2f

FOLLOWUP_NAME:  MachineOwner

MODULE_NAME: ntdll_77680000

IMAGE_NAME:  ntdll.dll

DEBUG_FLR_IMAGE_TIMESTAMP:  5c18dfc8

FAILURE_BUCKET_ID:  NULL_CLASS_PTR_READ_c0000005_ntdll.dll!__RtlUserThreadStart

BUCKET_ID:  APPLICATION_FAULT_NULL_CLASS_PTR_READ_INVALID_POINTER_READ_ZEROED_STACK_ntdll_77680000!__RtlUserThreadStart+2f

FAILURE_EXCEPTION_CODE:  c0000005

FAILURE_IMAGE_NAME:  ntdll.dll

BUCKET_ID_IMAGE_STR:  ntdll.dll

FAILURE_MODULE_NAME:  ntdll_77680000

BUCKET_ID_MODULE_STR:  ntdll_77680000

FAILURE_FUNCTION_NAME:  __RtlUserThreadStart

BUCKET_ID_FUNCTION_STR:  __RtlUserThreadStart

BUCKET_ID_OFFSET:  2f

BUCKET_ID_MODTIMEDATESTAMP:  5c18dfc8

BUCKET_ID_MODCHECKSUM:  19c1e0

BUCKET_ID_MODVER_STR:  10.0.17763.1098

BUCKET_ID_PREFIX_STR:  APPLICATION_FAULT_NULL_CLASS_PTR_READ_INVALID_POINTER_READ_ZEROED_STACK_

FAILURE_PROBLEM_CLASS:  APPLICATION_FAULT

FAILURE_SYMBOL_NAME:  ntdll.dll!__RtlUserThreadStart

WATSON_STAGEONE_URL:  http://watson.microsoft.com/StageOne/ab.exe/2.2.14.0/4a2cb3e6/unknown/0.0.0.0/bbbbbbb4/c0000005/005c3ae4.htm?Retriage=1

TARGET_TIME:  2020-12-18T20:41:26.000Z

OSBUILD:  17763

OSSERVICEPACK:  475

SERVICEPACK_NUMBER: 0

OS_REVISION: 0

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

OSEDITION:  Windows 10 WinNt SingleUserTS

USER_LCID:  0

OSBUILD_TIMESTAMP:  unknown_date

BUILDDATESTAMP_STR:  180914-1434

BUILDLAB_STR:  rs5_release

BUILDOSVER_STR:  10.0.17763.1.amd64fre.rs5_release.180914-1434

ANALYSIS_SESSION_ELAPSED_TIME:  5c44

ANALYSIS_SOURCE:  UM

FAILURE_ID_HASH_STRING:  um:null_class_ptr_read_c0000005_ntdll.dll!__rtluserthreadstart

FAILURE_ID_HASH:  {160bb105-c0c7-0bb1-2ada-adad72edd311}

Followup:     MachineOwner
---------
```
</details>

## Testing

Reproducing the original issue takes luck. Best I can suggest is trying to browse through a SOCKS proxy using Meterpreter and notice that this issue doesn't come up. From my testing there is still one or two much but I haven't been able to fully figure them out yet.

- [ ] Make a debug build using Visual Studio
- [ ] Open a Meterpreter session by running an EXE through WinDBG or load Debug View from SysInternals
- [ ] Add a route through the new session and run the SOCKS proxy module
- [ ] Browse the internet through Metasploit's SOCKS proxy (do a speed test, load twitter, watch a youtube video, try go get some serious throughput, it might be slow but it shouldn't crash)
- [ ] Don't see a crash from Meterpreter (at least not a NULL pointer dereference from a NULL channel)
- [ ] **Do** see debug logs

### CODE REVIEW

**Review by timwr — APPROVED** [review]
Looks sensible. I can't reproduce the original crash at the moment though.
Is there a plan to the expose the debug binaries under some kind of `MeterpreterDebug` option?

**Comment by timwr** [comment]
FYI: https://github.com/zeroSteiner/metasploit-payloads/pull/1

**Comment by zeroSteiner** [comment]
> Looks sensible. I can't reproduce the original crash at the moment though.

Yeah the crash was difficult and unreliable to reproduce in my testing. I experienced multiple crashes while testing the throughput but this once came up a couple of times.

> Is there a plan to the expose the debug binaries under some kind of MeterpreterDebug option?

No probably not right now. If we think it'd be useful though maybe we could in the future. My goal was mainly to prevent myself from having to make changes to version controlled files while debugging and fixing issues then having to split them all out when it was time to finish the thing.

**Comment by adfoster-r7** [comment]
@zeroSteiner This looks cool 🎉 

Bit of a drive-by question, do these docs need updated with any changes to the debugging steps?
https://github.com/rapid7/metasploit-payloads/wiki/Debugging-Meterpreter(s)

**Comment by zeroSteiner** [comment]
They're still relevant and accurate but switching the configuration in VS is easier and cleaner IMHO because it doesn't require a temporary change to a version controlled-file. I'll add a note about that option as well.

**Pull request merged**
