### PR TITLE
Fix address truncation occurring in x64 Windows processes.

### PR DESCRIPTION
**Pull request by plowsec**
While debugging a crash in _metsrv.x64.dll_, I noticed that `install_hooks` and `patch_function` use a _DWORD_ to hold a 64-bit address, and thus only the lower half of the address was actually used.

As per [Rules for Using Pointers](https://docs.microsoft.com/en-us/windows/win32/winprog64/rules-for-using-pointers), this is wrong and I can't believe no one else actually had problems with it.

As a result, `install_hooks` attempts to patch invalid addresses (0x4619FC50 instead of 0x7FFB4619FC50 on my system) and crashes the process.

### CODE REVIEW

**Comment by plowsec** [comment]
To add, if LoadLibraryR fails, libloader will try an alternative method and fail anyway. The bug I fixed above is only one of many.

**Comment by busterb** [comment]
This looks correct, but really do we need the casts at all?

**Comment by busterb** [comment]
Verified this is the right thing to do, thanks @plowsec

**Comment by OJ** [comment]
God damn pointer truncation bugs! **shakes fist**

**Pull request merged**
