### PR TITLE
Remove the old Mimikatz extension

### PR DESCRIPTION
**Pull request by OJ**
This commit removes all the source for the old Mimikatz extension. The Kiwi extension is the one that is maintained and updated, and it should support every OS that Meterpreter supports. Hence it doesn't make sense to keep it around. The source is painful to keep up to date with the new builds as well.

So, it's time to say goodbye. For more information, please refer to the [Metasploit Framework PR](https://github.com/rapid7/metasploit-framework/pull/13529).

This removes the source, the projects, the CMake files, etc.

I've also turned off PDB generation for the sniffer extension, as this was causing the build to spit out warnings.

### CODE REVIEW

**Comment by smcintyre-r7** [comment]
@msjenkins-r7 test this please

**Comment by OJ** [comment]
These conflicts be killing me, yo! :)

**Comment by OJ** [comment]
If you guys decide an order to merge these PRs into 6.x, I'll happily handle the conflicts as they come in. But I won't bother doing them until that decision is made. Is that ok @smcintyre-r7 @bcook-r7 @jmartin-r7 ?

**Comment by smcintyre-r7** [comment]
Thanks for address the merge conflicts! This is all set now and has been cleanly merged into 6.x.

**Comment by OJ** [comment]
Thank you!

**Pull request merged**
