### PR TITLE
Add Powershell extension

### PR DESCRIPTION
**Pull request by OJ**
This PR contains the Meterpreter-side code for the new Windows Powershell extension. Full details of the features of this extension can be found in the accompanying PR located on the MSF repository here: https://github.com/rapid7/metasploit-framework/pull/6691

Please may I request that general discussion of the feature set be had over on the MSF repo instead of this one. All technical and implementation detail can continue to be discussed here.

Thanks!

### CODE REVIEW

**Comment by OJ** [comment]
Note, this code contains a bunch of stuff that isn't in a repo at the moment. @bcook-r7 can we please create a new repo for this? I've pinged you behind the scenes to kick off the discussion. Thanks!

**Comment by OJ** [comment]
The extra component, which kind of belongs in this source base, but kind of doesn't, is currently hosted here: https://github.com/OJ/MSF.Powershell

@bcook-r7, thoughts on where this should belong and how it should be integrated?

**Comment by sempervictus** [comment]
Blows up on me:

```
meterpreter > load mirv
Loading extension mirv...success.
meterpreter > load python
Loading extension python...success.
meterpreter > load sniffer
Loading extension sniffer...success.
meterpreter > load lanattacks
Loading extension lanattacks...lsuccess.
meterpreter > load kiwi
Loading extension kiwi...load i

  .#####.   mimikatz 2.0 alpha (x86/windows) release "Kiwi en C"
 .## ^ ##.
 ## / \ ##  /* * *
 ## \ / ##   Benjamin DELPY `gentilkiwi` ( benjamin@gentilkiwi.com )
n '## v ##'   http://blog.gentilkiwi.com/mimikatz             (oe.eo)
  '#####'    Ported to Metasploit by OJ Reeves `TheColonial` * * */

	
[!] Loaded x86 Kiwi on an x64 architecture.
success.
meterpreter > load incognito
Loading extension incognito...losuccess.
meterpreter > load espia
Loading extension espia...success.
meterpreter > load extapi
Loading extension extapi...success.
meterpreter > load priv
Loading extension priv...success.
meterpreter > load mimikatz
Loading extension mimikatz...
[!] Loaded x86 Mimikatz on an x64 architecture.
success.
meterpreter > load powershell
Loading extension powershell...
[*] 10.0.0.40 - Meterpreter session 2 closed.  Reason: Died

```

Just rebuilt all extensions clean, not sure whats up, digging into it. The target is 2k8r2 VM, x64 in WOW mode.

**Comment by OJ** [comment]
That makes me sad. Lemme fire up a similar config.

**Comment by sempervictus** [comment]
@OJ: see IRC, i can give you access to this one.

**Comment by OJ** [comment]
@sempervictus This should be fixed now. Thanks for the help.

**Comment by bcook-r7** [comment]
building so more can play with it and we can land 0.1

**Comment by OJ** [comment]
Awesome, thanks Brent!

**Pull request merged**
