### PR TITLE
fix rapid7/metasploit-framework#13349

### PR DESCRIPTION
**Pull request by Abdulmanan0315**
Added code to ask for permissions on app startup;
Related to https://github.com/rapid7/metasploit-framework/issues/13349

### CODE REVIEW

**Comment by timwr** [comment]
Hi @Abdulmanan0315 were you able to build this?
I'm getting the following errors:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project Metasploit-AndroidPayload: Compilation failure: Compilation failure:
[ERROR] /metasploit-payloads/java/androidpayload/app/src/com/metasploit/stage/MainActivity.java:[38,42] cannot find symbol
[ERROR]   symbol:   class Context
[ERROR]   location: class com.metasploit.stage.MainActivity
[ERROR] /metasploit-payloads/java/androidpayload/app/src/com/metasploit/stage/MainActivity.java:[13,18] package Build does not exist
[ERROR] /metasploit-payloads/java/androidpayload/app/src/com/metasploit/stage/MainActivity.java:[13,43] package Build does not exist
[ERROR] /metasploit-payloads/java/androidpayload/app/src/com/metasploit/stage/MainActivity.java:[16,29] package Manifest does not exist
[ERROR] /metasploit-payloads/java/androidpayload/app/src/com/metasploit/stage/MainActivity.java:[17,29] package Manifest does not exist
[ERROR] /metasploit-payloads/java/androidpayload/app/src/com/metasploit/stage/MainActivity.java:[18,29] package Manifest does not exist
[ERROR] /metasploit-payloads/java/androidpayload/app/src/com/metasploit/stage/MainActivity.java:[19,29] package Manifest does not exist
[ERROR] /metasploit-payloads/java/androidpayload/app/src/com/metasploit/stage/MainActivity.java:[20,29] package Manifest does not exist
[ERROR] /metasploit-payloads/java/androidpayload/app/src/com/metasploit/stage/MainActivity.java:[21,29] package Manifest does not exist
[ERROR] /metasploit-payloads/java/androidpayload/app/src/com/metasploit/stage/MainActivity.java:[22,29] package Manifest does not exist
[ERROR] /metasploit-payloads/java/androidpayload/app/src/com/metasploit/stage/MainActivity.java:[23,29] package Manifest does not exist
[ERROR] /metasploit-payloads/java/androidpayload/app/src/com/metasploit/stage/MainActivity.java:[24,29] package Manifest does not exist
[ERROR] /metasploit-payloads/java/androidpayload/app/src/com/metasploit/stage/MainActivity.java:[25,29] package Manifest does not exist
[ERROR] /metasploit-payloads/java/androidpayload/app/src/com/metasploit/stage/MainActivity.java:[29,17] cannot find symbol
[ERROR]   symbol:   variable ActivityCompat
[ERROR]   location: class com.metasploit.stage.MainActivity
[ERROR] /metasploit-payloads/java/androidpayload/app/src/com/metasploit/stage/MainActivity.java:[41,21] cannot find symbol
[ERROR]   symbol:   variable ActivityCompat
[ERROR]   location: class com.metasploit.stage.MainActivity
[ERROR] /metasploit-payloads/java/androidpayload/app/src/com/metasploit/stage/MainActivity.java:[41,80] cannot find symbol
[ERROR]   symbol:   variable PackageManager
[ERROR]   location: class com.metasploit.stage.MainActivity
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :Metasploit-AndroidPayload
make: *** [Makefile:8: android] Error 1
```
I followed the build instructions here: https://github.com/rapid7/metasploit-payloads/tree/master/java

I think the ActivityCompat class is not included in the project yet.

**Comment by Abdulmanan0315** [comment]
@timwr I am sorry basically i am new to github and  i didn't built it. I know how to build something inside an android studio project but not this :(
And definitely The `ActivityCompat` class is required for the added code to work and i think it isn't included in the project yet.
I have a question Does the project supports android 10?
Can you provide me the **Compiled Project for android studio** so that i can take a look at it?

Thanks for your time 👍

**Comment by busterb** [comment]
I wonder if at some point we may need to have 2 different Android Meterpreters, or if we want to bump the base SDK again. We did it once before a few years ago once Android 2.x was mostly dead to SDK 17. Might make sense to bump TargetSdkVersion to 21 or 23 these days.

**Comment by smcintyre-r7** [comment]
I'm going to close this out since the consensus is that it is not building and there hasn't been any activity for quite some time.

**Pull request closed without merging**
