### PR TITLE
fix java/android download speed

### PR DESCRIPTION
**Pull request by timwr**
Fixes https://github.com/rapid7/metasploit-framework/issues/9541
It's not as fast as it could be but it's certainly an improvement.

### CODE REVIEW

**Comment by abdu791** [comment]
Please could you explain how to fix ? I didn't understand

**Comment by timwr** [comment]
You'll need to clone this repository next your metasploit-framework checkout, then build the java/android meterpreter it with this change.
https://github.com/rapid7/metasploit-payloads/tree/master/java

**Comment by timwr** [comment]
Alternatively just wait for us to test and merge the fix into metasploit-framework, then msfupdate

**Comment by abdu791** [comment]
Thank you for your replying
I will try the first way if don't work i will wait till you merge the fix
But please when you merge the fix tell us for do update
Thanks

**Comment by busterb** [comment]
This looks fine, landing.

**Comment by abdu791** [comment]
I upgraded to the latest update but it is still slow in downloading. How long will we wait to merge the fix?

**Pull request merged**
