### PR TITLE
update delete_dir to be able to recursively delete a directory if it is not empty

### PR DESCRIPTION
**Pull request by umerov1999**
Fix Error Open File VS2017 and Add Delete not empty Folder

### CODE REVIEW

**Comment by bwatters-r7** [comment]
Does this fix an issue?  Could you please add a description of what this fixes, and how we can verify it?

**Comment by busterb** [comment]
Yeah, this allows delete to work recursively, which is nice :)

**Comment by busterb** [comment]
This works, but it also doesn't throw an error if the directory doesn't exist.

**Comment by busterb** [comment]
Fixed it:
```
meterpreter > rmdir blah2
Removing directory: blah2
[-] stdapi_fs_delete_dir: Operation failed: The system cannot find the file specified.
meterpreter > rmdir blah
Removing directory: blah
```

**Pull request merged**
