### PR TITLE
Enable support of IPv6 address binding

### PR DESCRIPTION
**Pull request by OJ**
This PR contains some code that allows for the native Windows meterpreter to bind to both IPv4 and IPv6 addresses when TCP server channels are created. This isn't necessarily required for the reverse port forward feature to work, however it's good to be able to bind to both, just like we do with the stagers.

This new payload will result in the port being bound to both global addresses instead of just IPv4.

## Verification

- [x] use the MSF-side of the pull request https://github.com/rapid7/metasploit-framework/pull/6753
- [x] Build the payload.
- [x] Launch a session
- [x] Create a reverse port forward
- [x] Note that both IPv4 and IPv6 addresses are bound by the listener.

@bcook-r7 I'd love some help with POSIX testing if that's ok please.

### CODE REVIEW

**Comment by OJ** [comment]
OK, seems my local builds were _working_, yet they are clearly not working on Travis. Investigating.

**Comment by sempervictus** [comment]
While we're at this, we should probably take a look at how we pass/use socket options during binding. According to MSFT docs, raw sockets on UDP are allowed (to a degree), and so is socket reuse. We dont utilize these options, and so #6692 can't reuse remote sockets or properly serve DHCP on them.

**Comment by wchen-r7** [comment]
Testing this. This may take a while.

compiling

**Comment by wchen-r7** [comment]
I didn't land this because of the crash I ran into in #6753, and I have unassigned myself. I think @bcook-r7 will try to take a look again.

**Comment by OJ** [comment]
No problem. I'm looking into this right now. Thanks @wchen-r7 !

**Comment by bcook-r7** [comment]
Taking a look now...

**Comment by bcook-r7** [comment]
OK, let's get this going.

**Comment by OJ** [comment]
Awesome thank you Brent!

**Pull request merged**
