### PR TITLE
unicode conversion for incognito

### PR DESCRIPTION
**Pull request by busterb**
This is a WiP for the first half of https://github.com/rapid7/metasploit-framework/issues/8240

Still more cleanup to do, this has only been compile-tested so far.

### CODE REVIEW

**Comment by OJ** [comment]
Is this delayed at the moment @bcook-r7 ?

**Comment by busterb** [comment]
Other than having not actually tested it yet, it's good to go! I noticed some other bugs in incognito (or perhaps missing features), mostly around enumerating all of the potential flags available. But that doesn't have to be in scope for this PR.

**Comment by busterb** [comment]
Well, crash on first try, so I'm going to stick a delayed on until that's fixed.

**Comment by busterb** [comment]
I fixed all the bugs I could find. There were lots of 'sizeof == strlen' assumptions that still had needed fixing. This should be good to move forward now.

**Comment by FireFart** [comment]
@busterb so how do I get the metasploit-payload changes into my local metasploit-framework installation to test this?

Will try to find a german windows again :)

**Comment by busterb** [comment]
Assuming you can have built it, the short answer is have metasploit-payloads in the same directory as metasploit-framework, then type 'make install-windows'. It will copy to the right places in your metasploit-framework tree. To undo, rm metasploit-framework/data/meterpreter/*.dll

**Comment by busterb** [comment]
This seems to work fine for me, any objections to moving forward with it?

**Comment by OJ** [comment]
I'm happy to take this one!

**Comment by OJ** [comment]
Having said that, I don't have a german windows, so I might leave it to @FireFart :)

**Comment by FireFart** [comment]
@OJ @busterb still need to find an unpatched server at work to try this against :) Maybe we can try with a german ("Deutsch") version of Windows 10 evaluation? https://www.microsoft.com/software-download/windows10

**Comment by FireFart** [comment]
@OJ @busterb I wanted to try it against the free windows Internet Explorer test VMs but I can't get metasploit-payloads to build on a fresh win10 VM with Visual Studio Community 2017 and Visual Studio Express 2013 Update 5 installed in parallel :/

BTW: the download links in the meterpreter readme aren't working any more. You now need to join the "Dev Essentials Program" (https://www.visualstudio.com/dev-essentials/) and get the downloads from there (https://www.visualstudio.com/vs/older-downloads/).

Anyway:
If I'm trying to execute make.bat from the Visual Studio 2013 Command Prompt I get the following errors:
https://pastebin.com/CT44Yybh (Errors are at the bottom)

If I try to build it from within Visual Studio 2013 Express I get the following error (and a bunch of warnings):
https://pastebin.com/L0aeGLW7

Anyone has an idea what's the problem here?

PS: Windows Defender is disabled via the Settings app

**Comment by OJ** [comment]
@FireFart 
```
"Z:\hacking\metasploit-payloads\c\meterpreter\workspace\metsrv\metsrv.vcxproj" (Clean target) (6) ->
(CoreCppClean target) ->
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppClean.targets(76,5): warning : Access to the path
 'z:\hacking\metasploit-payloads\c\meterpreter\workspace\metsrv\release\win32\metsrv.x86.dll' is denied. [Z:\hacking\me
tasploit-payloads\c\meterpreter\workspace\metsrv\metsrv.vcxproj]
```
**Access denied** to your file system? These builds do indeed work cleanly locally mate (I just ran the myself 👍 ), so it's something local to your environment mate.

I'll go through the process of building clean using the free tools and re-document the process and update the readme. Thanks for the heads up!

**Comment by OJ** [comment]
@FireFart BTW, I had to disable Defender via policy. The settings app doesn't stop Defender for me.

**Comment by FireFart** [comment]
@OJ thanks for the hint! I disabled Windows Defender via 
```
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender
DisableAntiSpyware DWORD: 1
```
and now it's building correclty! Maybe also worth a hint in the readme

**Comment by OJ** [comment]
Yeah good idea @FireFart, I'll add that to the build steps!

**Comment by FireFart** [comment]
@busterb first tests with german win7 ultimate looks good so far:
a
are there any special things to test on this pr?

**Comment by FireFart** [comment]
I tested every incognito command except `snarf_hashes` and `add_group_user` and everything works fine so far. In my opinion the PR can be merged.

**Comment by busterb** [comment]
Thanks @FireFart !

**Comment by FireFart** [comment]
@busterb awesome!

**Pull request merged**
