### PR TITLE
Add `localtime` command support

### PR DESCRIPTION
**Pull request by OJ**
This PR (finally) adds the beginnings of the `localtime` command for Meterpreter. The aim of this command is to allow the user of a session to get the local system time of the machine that the session is running on. Details/discussion and MSF-side of the PR can be found over here: https://github.com/rapid7/metasploit-framework/pull/7423

Ping @timwr please, who kindly offered to do the Java/Android portion of this for me coz he's awesome.

@bcook-r7 and @acammack-r7 as mentioned in the MSF PR, I haven't added this to `mettle` yet. However, there's a small issue with POSIX thanks to Bionic not coughing up the correct time zone. Do you see this as a show stopper? It only does UTC 0 from what I can tell.

Marking as `delayed` while waiting for Tim.

### CODE REVIEW

**Comment by timwr** [comment]
@OJ Merging this should append the change here: https://github.com/OJ/metasploit-payloads/pull/6

**Comment by OJ** [comment]
No longer delayed thanks to @timwr :)

**Comment by bcook-r7** [comment]
so many tags!

**Comment by bcook-r7** [comment]
no show stopper - hope to have mettle pushed in here this week if we can.

**Comment by OJ** [comment]
I'm tag happy!

**Comment by bcook-r7** [comment]
Or as the Germans say, fröhliche Tag Tag!

**Pull request merged**
