### PR TITLE
Fix getprivs permissions that are grabbed on C Meterpreter and Python Meterpreter So That They Match

### PR DESCRIPTION
**Pull request by gwillcox-r7**
Fixes up the C Meterpreter and Python Meterpreter so that the `getprivs` command on both grabs the same set of permissions and in the same order.

On C Meterpreter we add the missing `SE_DELEGATE_SESSION_USER_IMPERSONATE_NAME` permission which was only being grabbed by the Python Meterpreter. 

On Python Meterpreter I reordered the permission list to match C Meterpreter, added comments to match the string names used to the `SE_*` names, and added the missing `SE_UNDOCK_NAME` and `SE_UNSOLICITED_INPUT_NAME` permissions as additional permissions to gather.

### CODE REVIEW

**Comment by jmartin-r7** [comment]
@msjenkins-r7 test this please.

**Comment by jmartin-r7** [comment]
```
11:06:32 "C:\Users\vagrant\metasploit-payloads\c\meterpreter\workspace\make.msbuild" (r7_all target) (1) ->
11:06:32 "C:\Users\vagrant\metasploit-payloads\c\meterpreter\workspace\meterpreter.sln" (Clean;Rebuild target) (2) ->
11:06:32 "C:\Users\vagrant\metasploit-payloads\c\meterpreter\workspace\screenshot\screenshot.vcxproj.metaproj" (Rebuild target) (18:2) ->
11:06:32 "C:\Users\vagrant\metasploit-payloads\c\meterpreter\workspace\screenshot\screenshot.vcxproj" (Rebuild target) (19:2) ->
11:06:32   C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(396,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\vagrant\metasploit-payloads\c\meterpreter\workspace\screenshot\screenshot.vcxproj]
11:06:32 
11:06:32 
11:06:32 "C:\Users\vagrant\metasploit-payloads\c\meterpreter\workspace\make.msbuild" (r7_all target) (1) ->
11:06:32 "C:\Users\vagrant\metasploit-payloads\c\meterpreter\workspace\meterpreter.sln" (Clean;Rebuild target) (2) ->
11:06:32 "C:\Users\vagrant\metasploit-payloads\c\meterpreter\workspace\ext_server_stdapi\ext_server_stdapi.vcxproj.metaproj" (Rebuild target) (22:2) ->
11:06:32 "C:\Users\vagrant\metasploit-payloads\c\meterpreter\workspace\ext_server_stdapi\ext_server_stdapi.vcxproj" (Rebuild target) (23:2) ->
11:06:32 (ClCompile target) -> 
11:06:32   ..\..\source\extensions\stdapi\server\sys\config\config.c(297): error C2065: 'SE_DELEGATE_SESSION_USER_IMPERSONATE_NAME' : undeclared identifier [C:\Users\vagrant\metasploit-payloads\c\meterpreter\workspace\ext_server_stdapi\ext_server_stdapi.vcxproj]
11:06:32 
11:06:32     19 Warning(s)
11:06:32     1 Error(s)
```

Are we sure this constant is available on the XP toolset?

**Comment by gwillcox-r7** [comment]
> SE_DELEGATE_SESSION_USER_IMPERSONATE_NAME

Hmm no, and its possible this may not have been defined. Will we need to manually define this value?

**Comment by gwillcox-r7** [comment]
Looks like it may have only been added to the documentation around 2019 or so: https://github.com/MicrosoftDocs/win32/commit/9a0fc9469bb1bae72a5afad80939d797fa452013

**Comment by jmartin-r7** [comment]
This PR suggests each of these is used to lookup a value so if we define it locally we may also need to add code to guard for if the OS does not provide the value, although I have not looked to validate if guards already exist.

**Comment by gwillcox-r7** [comment]
Earliest reference I can find using https://www.google.com/search?q=%22SeDelegateSessionUserImpersonatePrivilege%22&rlz=1C1GCEV_enUS901US901&source=lnt&tbs=cdr%3A1%2Ccd_min%3A1%2F1%2F2000%2Ccd_max%3A1%2F1%2F2009&tbm= for searching by dates is around 2008 for https://stackoverflow.com/questions/313831/using-powershell-how-do-i-grant-log-on-as-service-to-an-account so I'm guessing it was around since at least back then.

**Comment by smcintyre-r7** [comment]
[`LookupPrivilegeValueA`](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-lookupprivilegevaluea) returns an error code if the privilege can't be found which is already handled here.

I was able to request `SeDelegateSessionUserImpersonatePrivilege` when it was explicitly requested. It's just not defined in the headers in which case we should be able to add something along the lines of:

```c
#ifndef SE_DELEGATE_SESSION_USER_IMPERSONATE_PRIVILEGE
#define SE_DELEGATE_SESSION_USER_IMPERSONATE_PRIVILEGE TEXT("SeDelegateSessionUserImpersonatePrivilege")
#endif
```

Should note though that `TEXT` can create either ASCII or Wide strings, and is how the existing SE_ constants are defined. We treat them all as ASCII strings when we add them to the TLV response. This isn't a problem now but if the file is set to use wide strings in the future this would break. I think another acceptable solution for that reason would be to define all of the string constants ourselves as ASCII strings so our usage is guaranteed to use ASCII strings regardless of the file's build configuration.

**Review by smcintyre-r7 — APPROVED** [review]
Looks good to me, I'll get this landed.

<details>
<summary>Testing Output</summary>

### Server 2019
Shows that SeDelegateSessionUserImpersonatePrivilege is enabled.

```
[*] Meterpreter session 1 opened (192.168.159.128:4444 -> 192.168.159.10:52423) at 2023-02-28 14:22:57 -0500

meterpreter > getprivs 

Enabled Process Privileges
==========================

Name
----
SeAssignPrimaryTokenPrivilege
SeAuditPrivilege
SeBackupPrivilege
SeChangeNotifyPrivilege
SeCreateGlobalPrivilege
SeCreatePagefilePrivilege
SeCreatePermanentPrivilege
SeCreateSymbolicLinkPrivilege
SeDebugPrivilege
SeDelegateSessionUserImpersonatePrivilege
SeImpersonatePrivilege
SeIncreaseBasePriorityPrivilege
SeIncreaseQuotaPrivilege
SeIncreaseWorkingSetPrivilege
SeLoadDriverPrivilege
SeLockMemoryPrivilege
SeManageVolumePrivilege
SeProfileSingleProcessPrivilege
SeRestorePrivilege
SeSecurityPrivilege
SeShutdownPrivilege
SeSystemEnvironmentPrivilege
SeSystemProfilePrivilege
SeSystemtimePrivilege
SeTakeOwnershipPrivilege
SeTcbPrivilege
SeTimeZonePrivilege
SeUndockPrivilege

meterpreter > sysinfo
Computer        : DC
OS              : Windows 2016+ (10.0 Build 17763).
Architecture    : x64
System Language : en_US
Domain          : MSFLAB
Logged On Users : 7
Meterpreter     : x64/windows
meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > 
```

Can also see the output is alphabetized from Python now too:

```
meterpreter > getprivs

Enabled Process Privileges
==========================

Name
----
SeAssignPrimaryTokenPrivilege
SeAuditPrivilege
SeBackupPrivilege
SeChangeNotifyPrivilege
SeCreateGlobalPrivilege
SeCreatePagefilePrivilege
SeCreatePermanentPrivilege
SeCreateSymbolicLinkPrivilege
SeCreateTokenPrivilege
SeDebugPrivilege
SeDelegateSessionUserImpersonatePrivilege
SeEnableDelegationPrivilege
SeImpersonatePrivilege
SeIncreaseBasePriorityPrivilege
SeIncreaseQuotaPrivilege
SeIncreaseWorkingSetPrivilege
SeLoadDriverPrivilege
SeLockMemoryPrivilege
SeMachineAccountPrivilege
SeManageVolumePrivilege
SeProfileSingleProcessPrivilege
SeRelabelPrivilege
SeRemoteShutdownPrivilege
SeRestorePrivilege
SeSecurityPrivilege
SeShutdownPrivilege
SeSyncAgentPrivilege
SeSystemEnvironmentPrivilege
SeSystemProfilePrivilege
SeSystemtimePrivilege
SeTakeOwnershipPrivilege
SeTcbPrivilege
SeTimeZonePrivilege
SeTrustedCredManAccessPrivilege
SeUndockPrivilege

meterpreter > sysinfo
Computer        : DC
OS              : Windows 2016 (Build 17763)
Architecture    : x64
System Language : en_US
Meterpreter     : python/windows
meterpreter > 
```
</details>

**Pull request merged**
