### PR TITLE
remove unused imports

### PR DESCRIPTION
**Pull request by XenoAmess**

### CODE REVIEW

**Comment by gwillcox-r7** [comment]
Considering these are core changes to core files and there are some elements that could very well be needed, I'd be hesitant at the very least to make any of these changes. Some of these such as `com.metasploit.meterpreter.command.NotYetImplementedCommand` seem very suspicious to remove considering that this is our own code vs an external dependency and that line was likely added for a reason.

In this PR, and several others you haven't provided any explanation why changes to these critical files are needed beyond a brief one liner. Please make sure that this and all your other PRs have a description as to why the PR is needed, otherwise we will have to close them down if no further information is provided.

**Comment by XenoAmess** [comment]
```
Some of these such as `com.metasploit.meterpreter.command.NotYetImplementedCommand` seem very suspicious to remove considering that this is our own code vs an external dependency and that line was likely added for a reason.
```
@gwillcox-r7 so what reason can it be? I don't think an import can do anything, or maybe I be wrong?

**Comment by XenoAmess** [comment]
```
why the PR is needed
```
because I want to read clean and neet codes.
Of course you can close some of them if you think they are unreasonable.
All of the 17 prs today are suggestions, except a special one with a ```bug``` prefix, which seems a bug.

**Review by adfoster-r7 — APPROVED** [review]

**Comment by adfoster-r7** [comment]
@gwillcox-r7 Looks like that import existed when the implementation was different:
https://github.com/rapid7/metasploit-payloads/blame/a767fa2a2e4bda8b20c2dcd28a43b128c0277f38/java/_root/external/source/meterpreter/java/src/stdapi/com/metasploit/meterpreter/stdapi/stdapi_fs_file_expand_path.java#L13-L21

Now it just looks like an unused import. Java's imports are scoped to the current file, so it's not deleting the import entirely.

**Comment by gwillcox-r7** [comment]
> Java's imports are scoped to the current file, so it's not deleting the import entirely.

Ah my bad, misunderstanding on my part. I thought it might of still been being used but if the implementation has changed thats fine.

**Comment by timwr** [comment]
Thanks @XenoAmess , I've merged the obvious fixes.
I'm looking forward to any further improvements you might have.

**Pull request merged**
