### PR TITLE
Update to kiwi 2.2.0-20190813

### LINKED ISSUE #353: Update kiwi extension to Mimikatz 2.2.0-20190512
https://github.com/gentilkiwi/mimikatz/releases/tag/2.2.0-20190512

### PR DESCRIPTION
**Pull request by OJ**
As per the description, this updates the `kiwi` extension to the latest version as of today.

image

Fixes #353

### CODE REVIEW

**Comment by djcater** [comment]
@OJ @bcook-r7: is this likely to get merged soon? If not, it may make sense to rework the patch as a newer version has since been released (20191125): https://github.com/gentilkiwi/mimikatz/releases

**Comment by OJ** [comment]
I'll update this PR to include the new changes.

**Comment by busterb** [comment]
Want me to land this now @OJ or do you want to update first?

**Comment by busterb** [comment]
Taking a swag at updating - so far so good!

**Comment by OJ** [comment]
Thanks Brent. Thankfully that last update didn't bring any new files in.

Gotta change the version shown in framework now.

**Comment by busterb** [comment]
I checked before, it was all changes to existing files and no unwrapped prints.

**Comment by OJ** [comment]
Awesome

**Pull request merged**
