### PR TITLE
Stageless extension initialization

### PR DESCRIPTION
**Pull request by OJ**
This PR adds support for the invocation of "stuff" on each extension that is wired into a stageless payload. At the moment, the only extension that supports this is the `python` extension.

Extensions that have support for stageless initialisation receive a pointer to a blob of data that they should know how to handle themselves. In the case of the `python` extension, the data should be the content of a `.py` file. This file is _imported_ as if it was passed using `python_import` from within the Meterpreter console.

More information, verification, and sample runs can be found in the MSF PR, located here:  https://github.com/rapid7/metasploit-framework/pull/6264

### CODE REVIEW

**Comment by OJ** [comment]
Damn, Jenkins doesn't indicate success or failure of the build in its comments any more?

**Comment by busterb** [comment]
That jenkins server is a bit of an engima to me. Will see if we can give it a kick.

**Comment by bcook-r7** [comment]
Well, I haven't have a chance to dig into why the external jenkins didn't update, but this looks good to me. Will build a new gem for testing.

**Comment by OJ** [comment]
Thank you sir!

**Pull request merged**
