### PR TITLE
update build status link for windows meterpreter

### PR DESCRIPTION
**Pull request by bcook-r7**
This is a test PR, but also a functional one that should update the build status link for windows meterpreter.

### CODE REVIEW

**Comment by bcook-r7** [comment]
jenkins test this please

**Comment by cdoughty-r7** [comment]
jenkins test this please

**Comment by cdoughty-r7** [comment]
jenkins test this please

**Comment by cdoughty-r7** [comment]
jenkins test this please

**Comment by cdoughty-r7** [comment]
jenkins test this please

**Comment by bcook-r7** [comment]
jenkins test this please

**Pull request closed without merging**
